"""adding Reciklomat tables

Revision ID: 02f94bbdc4ad
Revises: 3b20d8df34b9
Create Date: 2024-10-12 16:14:23.990948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02f94bbdc4ad'
down_revision: Union[str, None] = '3b20d8df34b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reciklomatchangehistorys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reciklomat_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=100), nullable=False),
    sa.Column('new_status', sa.String(length=100), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reciklomatchangehistorys_reciklomat_id'), 'reciklomatchangehistorys', ['reciklomat_id'], unique=False)
    op.create_table('reciklomats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('occupancy', sa.Numeric(precision=4, scale=0), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=4, scale=0), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('lon', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reciklomatsubscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reciklomat_address', sa.String(length=500), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reciklomatsubscriptions_user_id'), 'reciklomatsubscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reciklomatsubscriptions_user_id'), table_name='reciklomatsubscriptions')
    op.drop_table('reciklomatsubscriptions')
    op.drop_table('reciklomats')
    op.drop_index(op.f('ix_reciklomatchangehistorys_reciklomat_id'), table_name='reciklomatchangehistorys')
    op.drop_table('reciklomatchangehistorys')
    # ### end Alembic commands ###
